In [1]:
import pandas as pd
df=pd.read_csv("employee_data.csv")

print(df)

      id groups  age  healthy_eating  active_lifestyle  salary
0      0      A   36               5                 5    2297
1      1      A   55               3                 5    1134
2      2      A   61               8                 1    4969
3      3      O   29               3                 6     902
4      4      O   34               6                 2    3574
5      5      O   42               5                 3    2761
6      6     AB   53               4                 6    1484
7      7      B   41               8                 6    3809
8      8      A   47               5                 6    2065
9      9      A   31               4                 8    1020
10    10      A   47               6                 9    1950
11    11      O   40               7                 1    4387
12    12      O   41               3                 2    1830
13    13      O   46               6                 8    2182
14    14     AB   51               7                 5    3460
15    15      B   57               3                 8     662
16    16      A   33               3                 5    1134
17    17      A   41               4                 8    1020
18    18      A   46               2                 6     779
19    19      O   32               7                 6    3228
20    20      O   57               7                 6    3228
21    21      O   26               1                 6    1360
22    22     AB   59               7                 5    3460
23    23      B   55               6                 4    3110
24    24      A   51               5                 8    1601
25    25      A   63               6                 7    2414
26    26      A   62               9                 6    4390
27    27      O   37               3                 5    1134
28    28      O   63               6                 7    2414
29    29      O   20               8                 6    3809
..   ...    ...  ...             ...               ...     ...
970  970      A   36               4                 8    1020
971  971      O   33               2                 8    1243
972  972      O   56               6                 3    3342
973  973      O   47               3                 6     902
974  974     AB   64              10                 5    5204
975  975      B   43               4                 6    1484
976  976      A   20               6                 4    3110
977  977      A   59               2                 6     779
978  978      A   61               3                 6     902
979  979      O   18               7                 8    2764
980  980      O   58               5                 5    2297
981  981      O   31               5                 9    1369
982  982     AB   50               9                 5    4622
983  983      B   29               5                 6    2065
984  984      A   32               3                 9     894
985  985      A   52               4                 3    2179
986  986      A   27               6                 7    2414
987  987      O   50               5                 5    2297
988  988      O   60               4                 6    1484
989  989      O   44               3                 5    1134
990  990     AB   20               3                 4    1366
991  991      B   38               8                 6    3809
992  992      A   30               6                 3    3342
993  993      A   56               5                 5    2297
994  994      A   52               5                 7    1833
995  995      O   33               7                 7    2996
996  996      O   21               1                 2     667
997  997      O   49               9                 7    4158
998  998     AB   56               6                 7    2414
999  999      B   64               4                 9     788

[1000 rows x 6 columns]

In [2]:
df1=df[0:1000].copy()
del df1['id']
del df1['groups']
del df1['salary']
#don't include salary too: Reason : Kmeans predictions requires all the features
#clustering has been done using all the relevant features except salary.
#Salary feature has been used in the regression
df1

     age  healthy_eating  active_lifestyle
0     36               5                 5
1     55               3                 5
2     61               8                 1
3     29               3                 6
4     34               6                 2
5     42               5                 3
6     53               4                 6
7     41               8                 6
8     47               5                 6
9     31               4                 8
10    47               6                 9
11    40               7                 1
12    41               3                 2
13    46               6                 8
14    51               7                 5
15    57               3                 8
16    33               3                 5
17    41               4                 8
18    46               2                 6
19    32               7                 6
20    57               7                 6
21    26               1                 6
22    59               7                 5
23    55               6                 4
24    51               5                 8
25    63               6                 7
26    62               9                 6
27    37               3                 5
28    63               6                 7
29    20               8                 6
..   ...             ...               ...
970   36               4                 8
971   33               2                 8
972   56               6                 3
973   47               3                 6
974   64              10                 5
975   43               4                 6
976   20               6                 4
977   59               2                 6
978   61               3                 6
979   18               7                 8
980   58               5                 5
981   31               5                 9
982   50               9                 5
983   29               5                 6
984   32               3                 9
985   52               4                 3
986   27               6                 7
987   50               5                 5
988   60               4                 6
989   44               3                 5
990   20               3                 4
991   38               8                 6
992   30               6                 3
993   56               5                 5
994   52               5                 7
995   33               7                 7
996   21               1                 2
997   49               9                 7
998   56               6                 7
999   64               4                 9

[1000 rows x 3 columns]

In [3]:
from sklearn.cluster import KMeans
di=0.0
di1=0.0

for i in range(2,30):
    kmeans = KMeans(n_clusters=i)
    kmeans.fit(df1)
    labels=kmeans.predict(df1)
    labels=list(labels)
    centroids=kmeans.cluster_centers_
    #print(centroids)
    min_=centroids[1]-centroids[0]
    min_squared=min_[0]**2+min_[1]**2+min_[2]**2
    min_squared=min_squared**.5
    #dunn's Index
    for j in range(len(centroids)):
        #calculating Minimum distance between clusters
        for k in range(j+1,len(centroids)):
            dist=centroids[k]-centroids[j]
            dist_squared=dist[0]**2+dist[1]**2+dist[2]**2
            dist_squared=dist_squared**.5
            if(dist_squared<min_squared):
                min_squared=dist_squared
    print(i)
    sum_=[]
    for j in range(len(centroids)):
        sum_.append(0)
    for j in range(len(labels)):
        #Calculating Delta
        for k in range(j+1,len(labels)):
            if(labels[j]==labels[k]):
                dist1=(df1.iloc[j]['age']-df1.iloc[j]['age'])**2+(df1.iloc[j]['healthy_eating']-df.iloc[k]['healthy_eating'])**2+(df1.iloc[j]['active_lifestyle']-df1.iloc[j]['active_lifestyle'])**2
            
                dist1_squared=dist1**.5
               
                sum_[labels[j]]=sum_[labels[j]]+dist1_squared
                
    for j in range(len(centroids)):
        cn=labels.count(j)
        sum_[j]=(sum_[j])/(cn) # cannot allow (cn-1) as division by zero may occur
            
    
    di=min_squared/max(sum_)
    print(di)

    if (di>di1):
        di1=di
        final_n=i
print("Optimal Number of Clusters = ",final_n)
   
kmeans = KMeans(n_clusters=final_n)
kmeans.fit(df1[0:900])
labels=kmeans.predict(df1[900:1000])   
labels1=kmeans.predict(df1[0:900])

2
0.04018963056539049
3
0.03867953797788701
4
0.037200337892061924
5
0.03791692438639678
6
0.031773143490260745
7
0.034081315813045736
8
0.033259447696475694
9
0.029929815756486792
10
0.02961350169788192
11
0.029939799845854428
12
0.03190769282799225
13
0.032117436041987135
14
0.03616352201257862
15
0.03354689691846267
16
0.043326335068989495
17
0.04371127309741884
18
0.0406363754481931
19
0.04233461625598046
20
0.041360214728297526
21
0.04769965436159884
22
0.061426562099704235
23
0.049708745912668544
24
0.05928958516968495
25
0.05819147774479954
26
0.08523575025647351
27
0.07929016138872089
28
0.07775651593830249
29
0.08230491890266647
Optimal Number of Clusters =  26

In [4]:
df2=pd.DataFrame()
df2['Labels']=labels

In [5]:
train_df=df[0:900].copy()
train_df['Labels']=labels1

In [6]:
test_df=df[900:1000].copy()
test_df['Labels']=labels
test_df

      id groups  age  healthy_eating  active_lifestyle  salary  Labels
900  900      O   39               6                 6    2646       0
901  901      O   50               7                 3    3923       3
902  902     AB   31               2                 3    1017      14
903  903      B   28               8                 7    3577       2
904  904      A   56               6                 5    2878      20
905  905      A   46               8                 7    3577      15
906  906      A   38               3                 4    1366      10
907  907      O   35               4                 7    1252      17
908  908      O   25               2                 5     553      21
909  909      O   35               3                 6     902      14
910  910     AB   21               2                 5     553      21
911  911      B   59               6                 6    2646      24
912  912      A   24               5                 3    2761      11
913  913      A   64               6                 5    2878       1
914  914      A   19               5                 1    3225      22
915  915      O   45               9                 6    4390      15
916  916      O   19               4                 6    1484       4
917  917      O   38               4                 7    1252      10
918  918     AB   25               9                 6    4390       8
919  919      B   26               4                 6    1484       2
920  920      A   64               5                 4    2529      25
921  921      A   43               3                 7     670      16
922  922      A   22               4                 4    1948      11
923  923      O   32               7                 6    3228       5
924  924      O   57               3                 8     662      23
925  925      O   57               2                 7    1011      23
926  926     AB   34               4                 3    2179      14
927  927      B   56               2                 5     553      23
928  928      A   44               6                 6    2646      15
929  929      A   26               7                 8    2764       8
..   ...    ...  ...             ...               ...     ...     ...
970  970      A   36               4                 8    1020      17
971  971      O   33               2                 8    1243      14
972  972      O   56               6                 3    3342       7
973  973      O   47               3                 6     902       9
974  974     AB   64              10                 5    5204      25
975  975      B   43               4                 6    1484      15
976  976      A   20               6                 4    3110      22
977  977      A   59               2                 6     779      23
978  978      A   61               3                 6     902      19
979  979      O   18               7                 8    2764       4
980  980      O   58               5                 5    2297      23
981  981      O   31               5                 9    1369       5
982  982     AB   50               9                 5    4622       3
983  983      B   29               5                 6    2065       2
984  984      A   32               3                 9     894       5
985  985      A   52               4                 3    2179       7
986  986      A   27               6                 7    2414       2
987  987      O   50               5                 5    2297       3
988  988      O   60               4                 6    1484      23
989  989      O   44               3                 5    1134       9
990  990     AB   20               3                 4    1366      22
991  991      B   38               8                 6    3809      10
992  992      A   30               6                 3    3342      18
993  993      A   56               5                 5    2297      20
994  994      A   52               5                 7    1833      20
995  995      O   33               7                 7    2996       5
996  996      O   21               1                 2     667      11
997  997      O   49               9                 7    4158       3
998  998     AB   56               6                 7    2414      20
999  999      B   64               4                 9     788       1

[100 rows x 7 columns]

In [7]:
sal_list=[]

sal=[]
from sklearn import linear_model
reg=linear_model.LinearRegression()

for i in range(0,100):
    j=test_df.iloc[i,6]    
    cluster=train_df[train_df.Labels==j]
    reg.fit(cluster[['age','healthy_eating','active_lifestyle']],cluster.salary)
    sal_list = reg.predict(test_df[i:i+1][['age','healthy_eating','active_lifestyle']])
    
    sal.append(sal_list[0])

In [8]:
test_df['pred_salary_modified']=sal

In [9]:
reg1=linear_model.LinearRegression()
reg.fit(train_df[['age','healthy_eating','active_lifestyle']],train_df.salary)
sal_list1 = reg.predict(test_df[['age','healthy_eating','active_lifestyle']])
test_df['pred_salary_global']  = sal_list1
test_df

,id,groups,age,healthy_eating,active_lifestyle,salary,Labels,pred_salary_modified,pred_salary_global
900,900,O,39,6,6,2646,0,2646.316240,2658.349810
901,901,O,50,7,3,3923,3,3923.548690,3660.687219
902,902,AB,31,2,3,1017,14,1301.172046,1381.570855
903,903,B,28,8,7,3577,2,3402.953534,3398.571783
904,904,A,56,6,5,2878,20,2878.233418,2830.835795
905,905,A,46,8,7,3577,15,3290.152465,3386.630887
906,906,A,38,3,4,1366,10,1366.346600,1651.507804
907,907,O,35,4,7,1252,17,1322.569240,1560.551587
908,908,O,25,2,5,553,21,1038.981123,1018.024157
909,909,O,35,3,6,902,14,1355.290558,1285.970956
910,910,AB,21,2,5,553,21,976.898348,1020.677690
911,911,B,59,6,6,2646,24,2646.213482,2645.082147
912,912,A,24,5,3,2761,11,2760.732907,2761.246923
913,913,A,64,6,5,2878,1,2839.028040,2825.528730
914,914,A,19,5,1,3225,22,3161.855659,3132.090835
915,915,O,45,9,6,4390,15,3933.518667,4029.401897
916,916,O,19,4,6,1484,4,1503.659088,1754.929215
917,917,O,38,4,7,1252,10,1251.988408,1558.561437
918,918,AB,25,9,6,4390,8,4390.396278,4042.669559
919,919,B,26,4,6,1484,2,1634.100597,1750.285533
920,920,A,64,5,4,2529,25,2528.567056,2550.948100
921,921,A,43,3,7,670,16,923.860914,1096.900393
922,922,A,22,4,4,1948,11,1947.636663,2120.466062
923,923,O,32,7,6,3228,5,3093.259229,3121.337620
924,924,O,57,3,8,662,23,774.479588,903.849531
925,925,O,57,2,7,1011,23,749.414176,629.268901
926,926,AB,34,4,3,2179,14,1457.207153,2296.268963
927,927,B,56,2,5,553,23,1235.001788,997.459281
928,928,A,44,6,6,2646,15,2566.126710,2655.032894
929,929,A,26,7,8,2764,8,2763.842834,2757.790922
...,...,...,...,...,...,...,...,...,...
970,970,A,36,4,8,1020,17,1113.196478,1376.124705
971,971,O,33,2,8,1243,14,1236.944718,461.426598
972,972,O,56,6,3,3342,7,3341.982842,3198.362791
973,973,O,47,3,6,902,9,1373.090731,1278.010359
974,974,AB,64,10,5,5204,25,5203.197887,4658.905244
975,975,B,43,4,6,1484,15,1655.822874,1739.008020
976,976,A,20,6,4,3110,22,2890.406324,3038.481086
977,977,A,59,2,6,779,23,901.200918,811.705633
978,978,A,61,3,6,902,19,990.803531,1268.722995
979,979,O,18,7,8,2764,4,2786.616975,2763.097987
980,980,O,58,5,5,2297,23,1911.169554,2371.164900
981,981,O,31,5,9,1369,5,1592.815330,1654.022251
982,982,AB,50,9,5,4622,3,4622.240279,4209.848479
983,983,B,29,5,6,2065,2,2062.890917,2206.639512
984,984,A,32,3,9,894,5,636.413908,736.670611
985,985,A,52,4,3,2179,7,2179.479903,2284.328067
986,986,A,27,6,7,2414,2,2418.906937,2482.546909
987,987,O,50,5,5,2297,3,2296.986377,2376.471965
988,988,O,60,4,6,1484,23,1364.113704,1727.730507
989,989,O,44,3,5,1134,9,1327.639376,1463.764007
990,990,AB,20,3,4,1366,22,1513.647986,1663.448700
991,991,B,38,8,6,3809,10,3808.849981,3575.701450
992,992,A,30,6,3,3342,18,3342.002296,3215.610753
993,993,A,56,5,5,2297,20,2296.916302,2372.491666
994,994,A,52,5,7,1833,20,1833.059796,2007.618202
995,995,O,33,7,7,2996,5,2915.716278,2936.910739
996,996,O,21,1,2,667,11,667.516977,1113.624056
997,997,O,49,9,7,4158,3,4158.315630,3842.984866
998,998,AB,56,6,7,2414,20,2414.295627,2463.308798
999,999,B,64,4,9,788,1,1006.002629,1173.786480

In [10]:
salary_original=list(test_df['salary'])
salary_predicted_modified=list(test_df['pred_salary_modified'])
salary_predicted_global = list(test_df['pred_salary_global'])

In [11]:
import numpy as np
from sklearn.metrics import mean_squared_error
rms_modified=mean_squared_error(salary_original,salary_predicted_modified)
rms_global = mean_squared_error(salary_original,salary_predicted_global)
rms_modified=rms_modified/np.array(salary_original).mean()
rms_global = rms_global/np.array(salary_original).mean()
print("NRMS for Modified Clustering = ",rms_modified)
print("NRMS for Global regression = ",rms_global)

NRMS for Modified Clustering =  16.994384702965974
NRMS for Global regression =  32.833571544760474